# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine:
      # specify the version you desire here
      image: ubuntu-2004:202104-01

    steps:
      - checkout

      - run:
          name: Analyze on SonarCloud
          command: gradle build sonarqube -x test

      - run: docker network create grid

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # download latest chrome/firefox elgalu images
      - run: docker pull elgalu/selenium

      # start selenium grid and wait until ready
      - run:
          command: |
            docker run --rm -d --name zalenium --net grid -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium start
            echo "export IP_ZALENIUM=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' zalenium)" >> $BASH_ENV
            echo $IP_ZALENIUM

      #wait until zalenium ready
      - run:
          command: |
            echo $IP_ZALENIUM
            wget --retry-connrefused --retry-on-http-error=502 -T 60 http://$IP_ZALENIUM:4444/wd/hub/status

      # run tests!
      - run:
          command: |
            echo $IP_ZALENIUM
            gradle test -DgridURL=http://$IP_ZALENIUM:4444/wd/hub

      - store_artifacts:
          path: ~/project/build/logs
          destination: logs
      - store_artifacts:
          path: ~/project/build/extent
          destination: extent
      - store_test_results:
          path: ~/project/build/extent
      - store_test_results:
          path: ~/project/build/reports/tests/test/junitreports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: SonarCloud
