name: Static Analysis

on: pull_request

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: runner / checkstyle
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run java checkstyle
      uses: nikitasavinov/checkstyle-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-check'
        level: error
